---
title: "Analyzing college major and income data"
author: "Braden Buchanan"
date: "2023-01-25"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
```

```{r}
recent_grads <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/college-majors/recent-grads.csv")

majors_processed <- recent_grads %>%
  arrange(desc(Median)) %>%
  mutate(Major = str_to_title(Major),
         Major = fct_reorder(Major, Median))
```

```{r}
recent_grads %>%
  view()
```

### Most common majors

What major categories (e.g. engineering, psychology, business) were most common?
```{r}
majors_processed %>%
  count(Major_category, wt = Total, sort = TRUE) %>%
  mutate(Major_category = fct_reorder(Major_category, n)) %>%
  ggplot(aes(Major_category, n, fill = Major_category)) +
  geom_col() +
  coord_flip() +
  labs(x = "",
       y = "Total # of graudates") +
  theme(legend.position = "none")
```

###What cateogies of majors make more money than others
Boxplot of the Medians
```{r}
majors_processed %>%
  mutate(Major_category = fct_reorder(Major_category, Median)) %>%
  ggplot(aes(Major_category, Median)) + 
  geom_boxplot() +
  scale_y_continuous(label = dollar_format()) +
  coord_flip()
```

Barchart of the medians
```{r}
majors_processed %>%
  mutate(Major_category = fct_reorder(Major_category, Median)) %>%
  group_by(Major_category) %>%
  summarize(Median = median(Median)) %>%
  ggplot(aes(Major_category, Median)) + 
  geom_col() +
  scale_y_continuous(label = dollar_format()) +
  coord_flip()
```



### What are the highest earning majors?
```{r}
majors_processed <- recent_grads %>%
  arrange(desc(Median)) %>%
  select(Major, Major_category, Median, P25th, P75th, Sample_size) %>%
  mutate(Major = str_to_title(Major),
         Major = fct_reorder(Major, Median))

majors_processed %>%
  head(20) %>%
  ggplot(aes(Major, Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  expand_limits(y = 0) +
  coord_flip()
```

What are the lowest earning majors?
```{r}
majors_processed %>%
  tail(20) %>%
  ggplot(aes(Major, Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  expand_limits(y = 0) +
  coord_flip()
```


### 
```{r}
install.packages("ggrepel")
library(ggrepel)

majors_processed %>%
  ggplot(aes(Sample_size, Median)) +
  geom_point() +
  geom_text(aes(label = Major), check_overlap = TRUE, vjust = 1, hjust = 1) +
  scale_x_log10()

majors_processed %>%
  filter(Sample_size >= 100) %>%
  head(20) %>%
  ggplot(aes(Major, Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip() +
  labs(title = "What are the highest-earning majors?",
       subtitle = "Top 20 majors with at least 100 graduates surveyed. Bars represent 25th and 75th percentile",
       y = "Median salary of graduates",
       x = "")
```


### How does gender breakdown relate to typical earnings?

```{r}
majors_processed %>%
  arrange(desc(Total))%>%
  head(20) %>%
  mutate(Major = fct_reorder(Major, Total)) %>%
  gather(Gender, Number, Men, Women) %>%
  select(Major, Gender, Number) %>%
  ggplot(aes(Major, Number, fill = Gender)) +
  geom_col() +
  scale_y_continuous(labels = comma_format()) +
  coord_flip()
```

```{r}
by_major_category <- majors_processed %>%
  filter(!is.na(Total)) %>%
  group_by(Major_category) %>%
  summarize(Men = sum(Men),
            Women = sum(Women),
            Total = sum(Total),
            MedianSalary = sum(Median * Sample_size)/sum(Sample_size)) %>%
  mutate(ShareWomen = Women/Total) %>%
  arrange(desc(ShareWomen))
```

```{r}
library(ggrepel)

by_major_category %>%
  ggplot(aes(ShareWomen, MedianSalary)) +
  geom_point() +
  geom_smooth(method ="lm") +
  geom_text_repel(aes(label = Major_category), force = .2) +
  expand_limits(y = 0)
```

```{r}
majors_processed %>%
  ggplot(aes(ShareWomen, Median)) +
  geom_point() +
  geom_smooth(method ="lm") +
  expand_limits(y = 0)
```

Weighted Linear Regression

```{r}
majors_processed %>%
  select(Major, Total, ShareWomen, Sample_size, Median) %>%
  lm(Median ~ ShareWomen, data = ., weights = Sample_size) %>%
  summary()
```

```{r}
majors_processed %>%
  select(Major, Major_category, Total, ShareWomen, Sample_size, Median) %>%
  add_count(Major_category) %>%
  filter(n >= 10) %>%
  count(Major_category)
```





