---
title: "Washington Trails"
author: "Braden Buchanan"
date: "2023-01-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

load data
```{r}
tuesdata <- tidytuesdayR::tt_load('2020-11-24')
```

Cleaning script - provided by authors
```{r}
tuesdata$hike_data
trailData <- tuesdata$hike_data %>%
  mutate(length_miles = parse_number(length)) %>%
  mutate(across(gain:rating, as.numeric)) %>%
  mutate(rating_grp = case_when(rating == 0 ~ "0",
                                rating >0 & rating < 2 ~ "1",
                                rating >=2 & rating < 3 ~ "2",
                                rating >=3 & rating < 4 ~ "3",
                                rating >=4 & rating < 5 ~ "4",
                                rating == 5 ~ "5")) %>%
  mutate(trail_type = case_when(grepl("roundtrip", length) ~ "Round trip",
                          grepl("one-way", length) ~ "One Way",
                          grepl("of trails", length) ~ "Trails")) %>% 
  mutate(location_split = location) %>%
  separate(location_split, c("location_region","location_specific"), sep = ' -- ') %>%
  mutate(features = lapply(features, sort, na.last = TRUE)) %>%
  mutate(feature_v = sapply(features,FUN = function(x) if (all(is.na(x))) NA else paste(x,collapse = ", "))) %>%
  mutate(feature_v = str_trim(feature_v)) %>%
  mutate(features_unnest = features) %>%
  unnest(cols = c(features_unnest), keep_empty = TRUE) %>% 
  mutate(feature_v = ifelse(is.na(feature_v), "none", feature_v)) %>%
  mutate(features_unnest = ifelse(is.na(features_unnest), "none", features_unnest)) %>%
  mutate(feature_init = case_when(features_unnest == "Dogs allowed on leash" ~ "DA",
                                  features_unnest == "Dogs not allowed" ~ "DN",
                                  features_unnest == "Wildlife" ~ "Wl",
                                  features_unnest == "Good for kids" ~ "GK",
                                  features_unnest == "Lakes" ~ "Lk",
                                  features_unnest == "Fall foliage" ~ "FF",
                                  features_unnest == "Ridges/passes" ~ "RP",
                                  features_unnest == "Established campsites" ~ "EC",
                                  features_unnest == "Mountain views" ~ "MV",
                                  features_unnest == "Old growth" ~ "OG",
                                  features_unnest == "Waterfalls" ~ "Wf",
                                  features_unnest == "Wildflowers/Meadows" ~ "WM",
                                  features_unnest == "Rivers" ~ "Ri",
                                  features_unnest == "Coast" ~ "Co",
                                  features_unnest == "Summits" ~ "Su")) %>%
  mutate(feature_init = ifelse(is.na(feature_init), "none", feature_init)) %>%
  mutate(feature_type = if_else(feature_init %in% c("DA","DN","GK"), "Companion", "Feature")) %>%
  mutate(feature_type = ifelse(feature_init == "none", "none", feature_type)) %>%
  group_by(name) %>%
  mutate(feature_n = n()) %>%
  ungroup() %>%
  mutate(feature_n = ifelse(feature_init == "none", 0, feature_n)) %>%
  select(name, location_region, location_specific, trail_type, length_miles, 
         gain, highpoint, rating, rating_grp, features, feature_v, features_unnest, 
         feature_init, feature_type, feature_n, description, location, length)
```


```{r}
view(trailData)
str(trailData)
head(trailData)
```

What are the longest hikes in Washington?
```{r}
trailData %>%
  select(name, location_region, length_miles, gain) %>%
  arrange(desc(length_miles)) %>%
  unique() %>%
  head(20)
```

How many unique hiking regions are there?
```{r}
trailData %>%
  select(location_region) %>%
  arrange(desc(location_region)) %>%
  unique()
```

How many total hikes are there in Washington?
```{r}
trailData %>%
  summarize(count = n_distinct(name))
```

What regions have the most hiking trails?
```{r}
trailData %>%
  group_by(location_region) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

trailData %>%
  filter(location_region == "North Cascades") %>%
  summarize(count=n_distinct(name))


trailData %>%
  group_by(location_region) %>%
  summarize(count=n_distinct(name)) %>%
  mutate(location_region = fct_reorder(location_region, count)) %>%
  ggplot(aes(location_region, count, fill = location_region)) +
  geom_col() +
  geom_text(aes(label = count), position = position_dodge(0.9), hjust = 1.2, color = "white") +
  labs(y = "Number of hikes",
       x = "Hiking regions",
       title = "Number of hikes per hiking region in Washington"
       ) + 
  coord_flip() + 
  theme(panel.background = element_blank(),
        legend.position = "none")
```

What hikes have the most elevation gain?
```{r}
trailData %>%
  filter(gain > 6000) %>%
  select(name, gain, length_miles) %>%
  distinct() %>%
  arrange(desc(gain)) %>%
  head(20)
```

Correlation between length_miles and gain
```{r}
trailData %>%
  ggplot(aes(length_miles, gain)) +
  geom_point() +
  labs(x = "Length of the hike (miles)", y = "Elevation gain (feet)", title = "Correlation between hike length and elevation gain") +
  theme_minimal()


outliers <- trailData %>%
  filter(gain > 6000) %>%
  select(name, gain, length_miles) %>%
  distinct() %>%
  mutate(outlier = ifelse(gain > quantile(gain, 0.75), "Outlier", "Not Outlier"))

# plot data with outliers labeled
ggplot(outliers, aes(x = length_miles, y = gain, color = outlier)) +
  geom_point() +
  geom_text(aes(label = ifelse(outlier == "Outlier", name, "")),
            hjust = 0, vjust = 0, size = 3) +
  ggtitle("Correlation between gain and length_miles") +
  xlab("Length (miles)") +
  ylab("Gain (feet)") +
  theme_classic()
```


