---
title: "Ulta Trail Running"
author: "Braden Buchanan"
date: "2023-02-21"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load packages
```{r}
library(tidyverse)
library(psych)
```

load data
```{r}
tuesdata <- tidytuesdayR::tt_load('2021-10-26')
tuesdata <- tidytuesdayR::tt_load(2021, week = 44)
```

View data
```{r}
rankings <- tuesdata$ultra_rankings
race <- tuesdata$race
```

Join data
```{r}
data <- inner_join(race, rankings, by = "race_year_id")
view(data)
```

Cleaning data
```{r}
str(data)
head(data$time)
head(data$start_time)
tail(data)

#lower casing all names
data$runner <- tolower(data$runner)
head(data$runner)

# Figuring out time
time_components <- strsplit(data$time, " ")
time_seconds <- sapply(lapply(time_components, function(x) {
  as.numeric(x[1])*3600 + as.numeric(x[2])*60 + as.numeric(x[3])
}), as.numeric)

head(data$time_seconds)
```


mutate(Major = fct_reorder(Major, Total)) %>%
What's the longest ultra?
```{r}
data %>%
  select(distance, race) %>%
  arrange(desc(distance)) %>%
  distinct() %>%
  head(25)
```

What's the shortest ultra?
```{r}
data %>%
  select(distance) %>%
  arrange(desc(distance)) %>%
  distinct() %>%
  tail(20)
```

Who has the most 1st places in ultras?
```{r}
data %>%
  select(runner, rank, country) %>%
  filter(rank == "1") %>%
  count(runner) %>%
  arrange(desc(n)) %>%
  mutate(runner = fct_reorder(runner, n)) %>%
  head(15) %>%
  ggplot(aes(n, runner)) +
  geom_col()
```

